# Generated by Django 6.0.2 on 2026-02-24 10:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=100)),
                ('deadline', models.DateField(db_index=True)),
                ('eligibility', models.CharField(choices=[('Open to All', 'Open to All'), ('Undergraduate Only', 'Undergraduate Only'), ('Graduate Only', 'Graduate Only'), ('International Students', 'International Students'), ('Domestic Students Only', 'Domestic Students Only'), ('STEM Students', 'STEM Students'), ('Arts & Humanities', 'Arts & Humanities'), ('First Year Students', 'First Year Students'), ('Final Year Students', 'Final Year Students'), ('Need-Based', 'Need-Based'), ('Merit-Based', 'Merit-Based')], db_index=True, default='Open to All', max_length=50)),
                ('description', models.TextField()),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='scholarships/thumbnails/')),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('applications_open', models.BooleanField(db_index=True, default=True)),
                ('application_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline'],
                'indexes': [models.Index(fields=['published', 'applications_open'], name='scholarship_publish_969682_idx'), models.Index(fields=['deadline'], name='scholarship_deadlin_f24616_idx')],
            },
        ),
    ]
