# Generated by Django 6.0.2 on 2026-02-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='thumbnail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
