# Generated by Django 6.0.2 on 2026-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('icon', models.CharField(choices=[('MdLocationCity', 'Campus/Location'), ('MdFlag', 'Foundation/Goal'), ('MdHistoryEdu', 'Charter/Academic'), ('MdEmojiEvents', 'Award/Achievement')], default='MdFlag', max_length=50)),
                ('category', models.CharField(choices=[('establishment', 'Establishment'), ('infrastructure', 'Infrastructure'), ('accreditation', 'Accreditation'), ('academic', 'Academic'), ('achievement', 'Achievement'), ('partnership', 'Partnership')], max_length=50)),
                ('significance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
