# Generated by Django 6.0.2 on 2026-03-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai', models.JSONField(blank=True, default=dict)),
                ('chat', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('security', models.JSONField(blank=True, default=dict)),
                ('scraping', models.JSONField(blank=True, default=dict)),
                ('maintenance', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
