# Generated by Django 6.0.2 on 2026-02-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(db_index=True, max_length=100)),
                ('school_name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(db_index=True, max_length=20)),
                ('semester', models.CharField(db_index=True, max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='published', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_by', models.CharField(default='admin', max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'semester', 'status'], name='timetable_t_school_b18ab4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(db_index=True, max_length=20)),
                ('unit_title', models.CharField(default='N/A', max_length=255)),
                ('lec_name', models.CharField(db_index=True, default='Staff', max_length=255)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], db_index=True, max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('room', models.CharField(db_index=True, default='ONLINE', max_length=50)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='timetable.timetable')),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'indexes': [models.Index(fields=['unit_code'], name='timetable_s_unit_co_4d2169_idx'), models.Index(fields=['room'], name='timetable_s_room_cc4602_idx'), models.Index(fields=['lec_name'], name='timetable_s_lec_nam_15c143_idx'), models.Index(fields=['timetable', 'day'], name='timetable_s_timetab_f5b700_idx')],
            },
        ),
    ]
