# Generated by Django 6.0.2 on 2026-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='programme',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='session',
            name='programme_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='campus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['programme'], name='timetable_s_program_62175c_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['programme_code'], name='timetable_s_program_36612e_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['campus', 'semester', 'status'], name='timetable_t_campus_083947_idx'),
        ),
    ]
