# Generated by Django 6.0.2 on 2026-02-24 10:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lead', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('Sciences', 'School of Sciences'), ('Tech', 'Information Technology'), ('Health', 'Health Sciences'), ('Arts', 'Humanities & Arts')], max_length=50)),
                ('funding', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Planning', 'Planning Phase'), ('Active', 'Active Research'), ('Peer Review', 'Under Peer Review'), ('Completed', 'Completed / Published')], default='Planning', max_length=20)),
                ('abstract', models.TextField(blank=True)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('collaborators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='research/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='research.researchproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['department'], name='research_re_departm_dd7af5_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['published'], name='research_re_publish_02bc8f_idx'),
        ),
    ]
