# Generated by Django 6.0.2 on 2026-02-28 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('website', 'Website URL'), ('sitemap', 'Sitemap URL'), ('pdf', 'PDF Document')], default='website', max_length=20)),
                ('url', models.URLField(blank=True, default='')),
                ('crawl_depth', models.IntegerField(default=1)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='crawler_pdfs/')),
                ('pdf_filename', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('chunk_count', models.IntegerField(default=0)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page_url', models.URLField(blank=True)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('embedding', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='crawler.crawlsource')),
            ],
            options={
                'ordering': ['source', 'id'],
            },
        ),
    ]
