# Generated by Django 6.0.2 on 2026-02-24 08:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('school', models.CharField(choices=[('ict', 'ICT'), ('business', 'Business'), ('engineering', 'Engineering'), ('health', 'Health'), ('education', 'Education')], db_index=True, max_length=50)),
                ('level', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('Professional Certification', 'Professional Certification')], db_index=True, max_length=50)),
                ('mean_grade', models.CharField(blank=True, max_length=10)),
                ('campuses', models.CharField(blank=True, max_length=255)),
                ('modes', models.CharField(blank=True, default='Full time, Part time, E-Learning', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('goal', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('duration_years', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_semesters', models.PositiveIntegerField(blank=True, null=True)),
                ('careers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('intake_months', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('January', 'January'), ('May', 'May'), ('September', 'September')], max_length=20), blank=True, default=list)),
                ('study_mode', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list)),
                ('accreditation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('units', models.JSONField(blank=True, default=list)),
                ('fee_structure', models.JSONField(blank=True, default=list)),
                ('career_paths', models.JSONField(blank=True, default=list)),
                ('entry_requirements', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['school', 'level'], name='programmes__school_bf0d74_idx'), models.Index(fields=['level', 'is_active'], name='programmes__level_ce93b0_idx')],
            },
        ),
    ]
