# Generated by Django 6.0.2 on 2026-03-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_alter_programme_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
