# Generated by Django 6.0.2 on 2026-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_alter_programme_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='fee_per_semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='semesters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
