# Generated by Django 6.0.2 on 2026-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_programmes', models.BooleanField(default=True)),
                ('use_faqs', models.BooleanField(default=True)),
                ('use_timetable', models.BooleanField(default=True)),
                ('use_research', models.BooleanField(default=True)),
                ('use_scholarships', models.BooleanField(default=True)),
                ('greeting_message', models.TextField(default="Hello! 👋 I'm your Zetech University assistant. How can I help you today?")),
                ('custom_system_prompt', models.TextField(blank=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Settings',
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('programmes', 'Programmes'), ('timetable', 'Timetable'), ('admissions', 'Admissions'), ('fees', 'Fees'), ('scholarships', 'Scholarships'), ('research', 'Research'), ('general', 'General'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('was_helpful', models.BooleanField(default=False)),
                ('had_timetable_results', models.BooleanField(default=False)),
                ('had_programme_results', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
