# Generated by Django 6.0.2 on 2026-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='use_external_sources',
            field=models.BooleanField(default=True),
        ),
    ]
