# Generated by Django 6.0.2 on 2026-03-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiconfig', '0002_aisettings_use_external_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aisettings',
            options={'verbose_name': 'AI Settings', 'verbose_name_plural': 'AI Settings'},
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='had_programme_results',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='had_timetable_results',
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='custom_system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='topic',
            field=models.CharField(choices=[('programmes', 'Programmes'), ('fees', 'Fees'), ('timetable', 'Timetable'), ('scholarships', 'Scholarships'), ('admissions', 'Admissions'), ('research', 'Research'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
