# Generated by Django 6.0.2 on 2026-03-09 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiconfig', '0003_alter_aisettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(choices=[('programmes', 'Programmes'), ('fees', 'Fees'), ('timetable', 'Timetable'), ('scholarships', 'Scholarships'), ('admissions', 'Admissions'), ('research', 'Research'), ('general', 'General')], max_length=50)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'topic'],
                'unique_together': {('date', 'topic')},
            },
        ),
    ]
