# Generated by Django 6.0.2 on 2026-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiconfig', '0004_dailystat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='fast_model',
            field=models.CharField(default='arcee-ai/trinity-mini:free', max_length=255),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='smart_model',
            field=models.CharField(default='arcee-ai/trinity-large-preview:free', max_length=255),
        ),
    ]
