# Generated by Django 6.0.2 on 2026-03-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiconfig', '0005_aisettings_fast_model_aisettings_smart_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatLog',
        ),
    ]
