# Generated by Django 6.0.2 on 2026-03-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='thumbnail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
